version: "3"
services:

  api-ingest:
    image: api-ingest
    ports:
      - '80:80'
    networks:
      - document-streaming
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - document-streaming

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - '9093:9093'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: CLIENT://:9092,EXTERNAL://:9093
      KAFKA_ADVERTISED_LISTENERS: CLIENT://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: CLIENT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - document-streaming

  spark:
    image: 'jupyter/pyspark-notebook:latest'
    ports:
      - '8888:8888'
      - "4040-4080:4040-4080"
    volumes:
      - ./ApacheSpark/:/users/ikennaughanze/work
    networks:
      - document-streaming

  mongo:
    container_name: mongo-dev
    image: mongo
    volumes:
      - ./data/mongodb:/data/db
    restart: on-failure
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: auth
    networks:
      - document-streaming

  mongo-express:
    image: mongo-express
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-dev
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: tribes
    networks:
      - document-streaming
    depends_on:
      - mongo
  streamlit-dashboard:
    image: dashboard
    ports:
      - '8501:8501'
    networks:
      - document-streaming

networks:
  document-streaming:
    driver: bridge